Boilerplate doc
vhive-serverless/STeLLAR pull request #290
Opened 2023-08-31 22:29 UTC by Ria

Add documentation for boiler plate.

Can you please check if you find this sufficient?

2023-09-01 01:12 UTC, kk-min approved these changes
Thanks! Left some suggestions

2023-09-01 01:12 UTC, kk-min commented on README.md
> +     - Takes the experiment.json file and assigns according values to Go Configuration struct.
```suggestion
     - Reads the experiment.json file and assigns values accordingly to Go Configuration struct.
```

2023-09-01 01:12 UTC, kk-min commented on README.md
> +     - Assigns endpoints and routes to each function deployed. Endpoints and routes are also stored in the Configuration struct. The enpoint values are extracted form the serverless framework deploy
```suggestion
     - Assigns endpoints and routes to each function deployed. Endpoint values are extracted from the Serverless framework deploy message and stored in the Configuration struct.
```

2023-09-01 01:12 UTC, kk-min commented on README.md
> +   - This package takes care of building Go binaries and Gradle projects for Java deployment.
```suggestion
   - This package takes builds Go binaries and Gradle projects for Java deployment.
```

2023-09-01 01:12 UTC, kk-min commented on README.md
> +   - This package contains legacy code from the original deployment implementation, which used provider specific APIs. Most of this package will be eventually obsolete, but we may get use of some of
```suggestion
   - This package contains legacy code from the original deployment implementation, which used provider specific APIs. Most of this package will be eventually obsolete and deprecated, but we may get use of some of its functionalities.
```

2023-09-01 01:12 UTC, kk-min commented on README.md
> +   - This package takes care of creating filler files, zipping of the function package and creation of artifacts.
```suggestion
   - This package creates filler files, zips function packages and creates artifacts.
```

2023-09-01 13:35 UTC, ypwong99 approved these changes
Lgtm

2023-09-06 01:38 UTC, ustiugov requested changes
commit history is a mess, please make a single commit and sign it.

2023-09-09 02:33 UTC, ypwong99 commented
> commit history is a mess, please make a single commit and sign it.

squashed and signed on @Ria's behalf

2023-09-10 08:54 UTC, merged