Refactor cicd test pipeline for more immediate results.
vhive-serverless/STeLLAR pull request #291
Opened 2023-09-01 14:40 UTC by Ria

2023-09-06 01:30 UTC, ustiugov approved these changes
LGTM. Min, can you take a look?

2023-09-06 01:30 UTC, ustiugov commented on .github/workflows/feature-serverless-framework-deployment.yml
> +        run: go test -short -v ./setup/deployment/connection/...
please use `matrix` to avoid duplication and to run them in parallel
https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs

2023-09-06 01:30 UTC, ustiugov commented
please squash alll commits into a single one

2023-09-06 01:31 UTC, ustiugov requested changes
please squash the commits and sign them

2023-09-07 10:29 UTC, kk-min requested changes
Currently each module's unit test is a step under 1 job called `unit_tests`; unfortunately we [cannot run steps in parallel](https://github.com/orgs/community/discussions/26291) so they need to be changed to jobs (1 job for each module's test)

To run them in parallel with a matrix, we can try storing the path (since all the steps run `go test -short -v <path>` in the matrix:

```yml
jobs:
  unit_tests: 
    strategy:
      matrix:
        path: [./setup/test/..., ./benchmarking/..., ./util/..., etc.]
    steps:
      //checkout, etc.
      - name: Run Unit test
        working-directory: ${{env.working-directory}}
        run: go test -short -v ${{matrix.path}}
```

2023-09-10 08:56 UTC, ustiugov approved these changes

2023-09-10 08:56 UTC, ustiugov commented
please merge when ready

2023-09-10 09:06 UTC, ypwong99 approved these changes

2023-09-10 09:21 UTC, merged